backend:
  name: github
  repo: your-username/your-repo-name
  branch: main

media_folder: "Images"
public_folder: "/Images"

collections:
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - label: "Bento Grids"
        name: "bentoGrids"
        widget: "list"
        fields:
          - {label: "Layout", name: "layout", widget: "select", options: ["default", "alternate-1", "alternate-2"]}
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - {label: "Image", name: "src", widget: "image"}
              - {label: "Alt Text", name: "alt", widget: "string"}
              - {label: "Type", name: "type", widget: "select", options: ["central", "secondary"]}
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
